# ========== Profile ========== #
# avatar
avatar: /avatar/kumamon.jpg
# author name
author: fi3ework
# signature
signature: witness me
# SNS
social:
  email: 12345@qq.com
  github: //github.com/fi3ework
  weibo:
  # zhihu:
  # facebook:
  # twitter:
  # instagram:
  # stack-overflow:
  # linkedin:
# friends
friends:
  friendA: //www.baidu.com
  friendB: //www.google.com
  # friendC :

# ========== Site ========== #
# title of the site
SEO_title: fi3ework's Studio
# main title
main_title: fi3ework's Studio.
# subtitle
subtitle: it's better to burn out than to fade away
# site haeder image
site_header_image: 'http://oumn0o088.bkt.clouddn.com/intro-desktop.jpg'
# post haeder image
post_header_image: 'http://oumn0o088.bkt.clouddn.com/post-bg.jpg'
# 404 image
_404_image: 'http://oumn0o088.bkt.clouddn.com/404.jpg'

# ========== Comment ========== #
# 目前只支持一键添加livere评论（因为懒），其他评论插件可自行添加
comment:
  # change the value of livere to your livere data-uid
  livere:

# ========== Analytics ========== #
# Busuanzi pv Analytics
busuanzi: false
# Baidu analytics
baidu_analytics:
# Google analytics
google_analytics:
# CNZZ analytics
CNZZ_analytics:

# ========== Others ========== #
# favicon
favicon: /assests/favicon.ico
# truncate length (the default is 300)
truncate_length:
