menu:
  Home: /
  Tags: /tags
  Archives: /archives
  About: /about

updateLogo: logo.svg

# ===========================================
# Social links Settings
# ===========================================
social:
  email: 805843200@qq.com
  facebook: fi3ework@github.io
  twitter: fi3ework@github.io
  github: fi3ework@github.io
  linkedin: fi3ework@github.io
  zhihu: www.zhihu.com/people/Firework_wee
  weibo: weibo.com/u/2612303102
  google: fi3ework@github.io
  stack-overflow: fi3ework@github.io
  blog: weibo.com/u/2612303102