menu:
  Home: /

# ===========================================
# Social links Settings
# ===========================================
social:
  email: 123456@qq.com
  facebook: //github.com/fi3ework
  twitter: //github.com/fi3ework
  github: //github.com/fi3ework
  instagram: //github.com/fi3ework
  linkedin: //github.com/fi3ework
  zhihu: //github.com/fi3ework
  weibo: //github.com/fi3ework
  stack-overflow: //github.com/fi3ework
# ===========================================
# friends
# ===========================================
friends:
  winter : www.baidu.com
  summer : www.baidu.com
  spring : www.baidu.com
  autumn : www.baidu.com
# ===========================================
# avatar
# ===========================================
avatar: /assets/avatar/kumamon.jpg