# ========== Profile ========== #
# avatar
avatar: /assets/avatar/kumamon.jpg
# author name
author: WEE
# signature
signature: witness me
# SNS
social:
  email: 805843200@qq.com
  github: //github.com/fi3ework
  weibo: //weibo.com/p/1005052612303102
  # zhihu:
  # facebook:
  # twitter:
  # instagram:
  # stack-overflow:
  # linkedin:
# friends
friends:
  Mason Zhou: https://github.com/Mason1993
  Wang Tao: https://github.com/wwtdsg
  # friendC :

# ========== Site ========== #
# title of the site
SEO_title: FIREWORK STUDIO
# main title
main_title: firework's Studio.
# subtitle
subtitle: it's better to burn out than fade away
# background image
header_image: /assets/background/bg-desktop.jpg

# ========== Comment ========== #
# 目前只支持一键添加livere评论（因为懒），其他评论插件可自行添加
comment:
  # change the value of livere to your livere data-uid
  livere: MTAyMC8yODQyOS81MDAw

# ========== Analytics ========== #
# Busuanzi pv Analytics
busuanzi: true
# Baidu analytics
baidu_analytics: 'https://hm.baidu.com/hm.js?c2e692c5407f95609121a9d80bd24510'
# Google analytics
google_analytics: 'UA-103985966-1'
# CNZZ analytics
CNZZ_analytics: '1263255655'

# ========== Others ========== #
# favicon
favicon: /assets/favicon.ico
# truncate length (the default is 300)
truncate_length:
