menu:
  Home: /

updateLogo: logo.svg
# ===========================================
# Social links Settings
# ===========================================
social:
  email: 805843200@qq.com
  facebook: www.zhihu.com/people/Firework_wee
  twitter: www.zhihu.com/people/Firework_wee
  github: www.zhihu.com/people/Firework_wee
  instagram: www.zhihu.com/people/Firework_wee
  linkedin: www.zhihu.com/people/Firework_wee
  zhihu: www.zhihu.com/people/Firework_wee
  weibo: weibo.com/u/2612303102
  stack-overflow: www.zhihu.com/people/Firework_wee
# ===========================================
# friends
# ===========================================
friends:
  winter : www.baidu.com
  summer : www.baidu.com
  spring : www.baidu.com
  autumn : www.baidu.com
# ===========================================
# avatar
# ===========================================
avatar: /assets/avatar/kumamon.jpg