menu:
  Home: /

updateLogo: logo.svg
# ===========================================
# Social links Settings
# ===========================================
social:
  email: 805843200@qq.com
  facebook: http://www.zhihu.com/people/Firework_wee
  twitter: http://www.zhihu.com/people/Firework_wee
  github: http://www.zhihu.com/people/Firework_wee
  instagram: http://www.zhihu.com/people/Firework_wee
  linkedin: http://www.zhihu.com/people/Firework_wee
  zhihu: http://www.zhihu.com/people/Firework_wee
  weibo: http://weibo.com/u/2612303102
  stack-overflow: http://www.zhihu.com/people/Firework_wee
# ===========================================
# friends
# ===========================================
friends:
  winter : www.baidu.com
  summer : www.baidu.com
  spring : www.baidu.com
  autumn : www.baidu.com
# ===========================================
# avatar
# ===========================================
avatar: /assets/avatar/kumamon.jpg